VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "UniCodeConst"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' List friendly names of Unicode characters
Public Enum eUnicodeConst
    RightArrow
    LeftArrow
    Clock2
    CheckOK
    Ghost
    MapleLeaf
    Calaca
    Corazon
    Finger1
    Handbro
    SailBoat
    Airplane
    XMark
    Umbrella
    PeaceLove
    DogFace
    
End Enum
